### ISSUE TITLE
Could you please add a license?

### ISSUE THREAD

**Issue by atinsley** [nmelo/alexa-appkit-lights#1]
Nmelo,

I forked your code to create a simple barebones Alexa Skills Kit endpoint without realizing you didn't have a license on here.  I was going to release mine under the MIT license or whatever you think is best, but I can't do that without you first having a license.

Obviously, my choice of license would be dependent on yours. And if you don't want to add a license,  I'll simply take a few minutes and rewrite the code I borrowed from you (though I like it!).  Could you please add a license?

Thanks a lot.

**Comment by nmelo** [comment]
Sorry, didn't see this issue until now! Added an MIT license file. 
Thanks for asking!
